# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visiteur.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_visiteur(object):
    def setupUi(self, MainWindow_visiteur):
        MainWindow_visiteur.setObjectName("MainWindow_visiteur")
        MainWindow_visiteur.resize(491, 616)
        MainWindow_visiteur.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow_visiteur)
        self.centralwidget.setObjectName("centralwidget")
        self.CIN_input = QtWidgets.QLineEdit(self.centralwidget)
        self.CIN_input.setGeometry(QtCore.QRect(270, 80, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CIN_input.setFont(font)
        self.CIN_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.CIN_input.setObjectName("CIN_input")
        self.NOM_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NOM_input.setGeometry(QtCore.QRect(30, 180, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NOM_input.setFont(font)
        self.NOM_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.NOM_input.setObjectName("NOM_input")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(190, 480, 121, 71))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(40, 480, 121, 71))
        self.Delete_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("#Delete_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Delete_btn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(340, 480, 121, 71))
        self.Add_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("#Add_btn{\n"
"background-color: rgb(112, 162, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(17, 21, 255);\n"
"}\n"
"#Add_btn:hover:pressed{\n"
"background-color: rgb(190, 164, 255);\n"
"}")
        self.Add_btn.setObjectName("Add_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 0, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(43)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(9, 28, 149);")
        self.label.setObjectName("label")
        self.ADRESSE_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ADRESSE_input.setGeometry(QtCore.QRect(30, 280, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ADRESSE_input.setFont(font)
        self.ADRESSE_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.ADRESSE_input.setObjectName("ADRESSE_input")
        self.PRENOM_input = QtWidgets.QLineEdit(self.centralwidget)
        self.PRENOM_input.setGeometry(QtCore.QRect(270, 180, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PRENOM_input.setFont(font)
        self.PRENOM_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.PRENOM_input.setObjectName("PRENOM_input")
        self.TEL_input = QtWidgets.QLineEdit(self.centralwidget)
        self.TEL_input.setGeometry(QtCore.QRect(270, 280, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TEL_input.setFont(font)
        self.TEL_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.TEL_input.setObjectName("TEL_input")
        self.EMAIL_input = QtWidgets.QLineEdit(self.centralwidget)
        self.EMAIL_input.setGeometry(QtCore.QRect(30, 380, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EMAIL_input.setFont(font)
        self.EMAIL_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.EMAIL_input.setObjectName("EMAIL_input")
        self.NUM_VISITEUR_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NUM_VISITEUR_input.setGeometry(QtCore.QRect(30, 80, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NUM_VISITEUR_input.setFont(font)
        self.NUM_VISITEUR_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.NUM_VISITEUR_input.setObjectName("NUM_VISITEUR_input")
        MainWindow_visiteur.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_visiteur)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 29))
        self.menubar.setObjectName("menubar")
        MainWindow_visiteur.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_visiteur)
        self.statusbar.setObjectName("statusbar")
        MainWindow_visiteur.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_visiteur)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_visiteur)

    def retranslateUi(self, MainWindow_visiteur):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_visiteur.setWindowTitle(_translate("MainWindow_visiteur", "MainWindow"))
        self.CIN_input.setPlaceholderText(_translate("MainWindow_visiteur", "CIN"))
        self.NOM_input.setPlaceholderText(_translate("MainWindow_visiteur", "NOM"))
        self.Search_btn.setText(_translate("MainWindow_visiteur", "Search "))
        self.Delete_btn.setText(_translate("MainWindow_visiteur", "Delete "))
        self.Add_btn.setText(_translate("MainWindow_visiteur", "Add "))
        self.label.setText(_translate("MainWindow_visiteur", "Visiteur"))
        self.ADRESSE_input.setPlaceholderText(_translate("MainWindow_visiteur", "ADRESSE"))
        self.PRENOM_input.setPlaceholderText(_translate("MainWindow_visiteur", "PRENOM"))
        self.TEL_input.setPlaceholderText(_translate("MainWindow_visiteur", "TEL"))
        self.EMAIL_input.setPlaceholderText(_translate("MainWindow_visiteur", "EMAIL"))
        self.NUM_VISITEUR_input.setPlaceholderText(_translate("MainWindow_visiteur", "NUM_VISITEUR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_visiteur = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_visiteur()
    ui.setupUi(MainWindow_visiteur)
    MainWindow_visiteur.show()
    sys.exit(app.exec_())
