# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lists.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lists_MainWindow(object):
    def setupUi(self, Lists_MainWindow):
        Lists_MainWindow.setObjectName("Lists_MainWindow")
        Lists_MainWindow.resize(720, 652)
        Lists_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Lists_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.User_Id_input = QtWidgets.QLineEdit(self.centralwidget)
        self.User_Id_input.setGeometry(QtCore.QRect(20, 100, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.User_Id_input.setFont(font)
        self.User_Id_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.User_Id_input.setText("")
        self.User_Id_input.setObjectName("User_Id_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(43)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(9, 28, 149);")
        self.label.setObjectName("label")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(310, 100, 191, 81))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.Clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_btn.setGeometry(QtCore.QRect(520, 100, 171, 81))
        self.Clear_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Clear_btn.setFont(font)
        self.Clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Clear_btn.setStyleSheet("#Clear_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Clear_btn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.Clear_btn.setObjectName("Clear_btn")
        self.ClientInformation_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ClientInformation_listWidget.setGeometry(QtCore.QRect(10, 280, 341, 311))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ClientInformation_listWidget.setFont(font)
        self.ClientInformation_listWidget.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.ClientInformation_listWidget.setObjectName("ClientInformation_listWidget")
        self.ClientReservation_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ClientReservation_listWidget.setGeometry(QtCore.QRect(360, 280, 341, 311))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ClientReservation_listWidget.setFont(font)
        self.ClientReservation_listWidget.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(149, 255, 110);")
        self.ClientReservation_listWidget.setObjectName("ClientReservation_listWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 230, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(9, 28, 149);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(9, 28, 149);")
        self.label_3.setObjectName("label_3")
        Lists_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Lists_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 29))
        self.menubar.setObjectName("menubar")
        Lists_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Lists_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Lists_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Lists_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Lists_MainWindow)

    def retranslateUi(self, Lists_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Lists_MainWindow.setWindowTitle(_translate("Lists_MainWindow", "MainWindow"))
        self.User_Id_input.setPlaceholderText(_translate("Lists_MainWindow", "User Id"))
        self.label.setText(_translate("Lists_MainWindow", "Clients Lists :"))
        self.Search_btn.setText(_translate("Lists_MainWindow", "Search "))
        self.Clear_btn.setText(_translate("Lists_MainWindow", "Clear "))
        self.label_2.setText(_translate("Lists_MainWindow", "Client reservations :"))
        self.label_3.setText(_translate("Lists_MainWindow", "Client Information :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lists_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Lists_MainWindow()
    ui.setupUi(Lists_MainWindow)
    Lists_MainWindow.show()
    sys.exit(app.exec_())
