# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reservation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate 



class Ui_RESERVATIONMainWindow(object):
    def setupUi(self, RESERVATIONMainWindow):
        RESERVATIONMainWindow.setObjectName("RESERVATIONMainWindow")
        RESERVATIONMainWindow.resize(1870, 1040)
        self.centralwidget = QtWidgets.QWidget(RESERVATIONMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(1440, 310, 411, 71))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.NUM_CHAMBRE_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NUM_CHAMBRE_input.setGeometry(QtCore.QRect(30, 230, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NUM_CHAMBRE_input.setFont(font)
        self.NUM_CHAMBRE_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.NUM_CHAMBRE_input.setObjectName("NUM_CHAMBRE_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 0, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(9, 28, 149);")
        self.label.setObjectName("label")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(1440, 130, 411, 71))
        self.Add_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("#Add_btn{\n"
"background-color: rgb(112, 162, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(17, 21, 255);\n"
"}\n"
"#Add_btn:hover:pressed{\n"
"background-color: rgb(190, 164, 255);\n"
"}")
        self.Add_btn.setObjectName("Add_btn")
        self.NUM_VISITEUR_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NUM_VISITEUR_input.setGeometry(QtCore.QRect(420, 120, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NUM_VISITEUR_input.setFont(font)
        self.NUM_VISITEUR_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.NUM_VISITEUR_input.setObjectName("NUM_VISITEUR_input")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(1440, 220, 411, 71))
        self.Delete_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("#Delete_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Delete_btn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.NUM_RESERVATION_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NUM_RESERVATION_input.setGeometry(QtCore.QRect(30, 120, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NUM_RESERVATION_input.setFont(font)
        self.NUM_RESERVATION_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.NUM_RESERVATION_input.setText("")
        self.NUM_RESERVATION_input.setObjectName("NUM_RESERVATION_input")
        
        # self.DATE_FIN = QtWidgets.QDateEdit(self.centralwidget)
                        
        self.DATE_FIN = QtWidgets.QDateEdit(QDate.currentDate(), self.centralwidget)
        



        self.DATE_FIN.setGeometry(QtCore.QRect(420, 380, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DATE_FIN.setFont(font)
        self.DATE_FIN.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.DATE_FIN.setObjectName("DATE_FIN")
        
        
        self.DATE_DEB = QtWidgets.QDateEdit(QDate.currentDate(), self.centralwidget)

        # self.DATE_DEB = QtWidgets.QDateEdit(self.centralwidget)        

        self.DATE_DEB.setGeometry(QtCore.QRect(30, 380, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DATE_DEB.setFont(font)
        self.DATE_DEB.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.DATE_DEB.setObjectName("DATE_DEB")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 320, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(9, 28, 149);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 320, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(9, 28, 149);")
        self.label_3.setObjectName("label_3")
        self.Reservation_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.Reservation_listWidget.setGeometry(QtCore.QRect(790, 130, 551, 431))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Reservation_listWidget.setFont(font)
        self.Reservation_listWidget.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.Reservation_listWidget.setObjectName("Reservation_listWidget")
        self.Clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_btn.setGeometry(QtCore.QRect(1440, 400, 411, 71))
        self.Clear_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Clear_btn.setFont(font)
        self.Clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Clear_btn.setStyleSheet("#Clear_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 112, 10);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Clear_btn:hover:pressed{\n"
"background-color: rgb(158, 182, 186);\n"
"}\n"
"")
        self.Clear_btn.setObjectName("Clear_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(790, 80, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(9, 28, 149);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 460, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(9, 28, 149);")
        self.label_5.setObjectName("label_5")
        self.Price = QtWidgets.QLabel(self.centralwidget)
        self.Price.setGeometry(QtCore.QRect(240, 460, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Price.setFont(font)
        self.Price.setStyleSheet("color: rgb(226, 0, 0);")
        self.Price.setObjectName("Price")
        self.showChambre_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.showChambre_Btn.setGeometry(QtCore.QRect(420, 230, 331, 81))
        self.showChambre_Btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.showChambre_Btn.setFont(font)
        self.showChambre_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showChambre_Btn.setStyleSheet("#showChambre_Btn {\n"
"    border: 3px solid rgb(3, 168, 17);\n"
"    border-radius: 18px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #ff0000, stop:0.17 #ff7f00, stop:0.33 #ffff00, stop:0.5 #00ff00, stop:0.67 #0000ff, stop:0.83 #4b0082, stop:1 #8f00ff);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#showChambre_Btn:hover:pressed {\n"
"    background-color: rgb(126, 255, 103);\n"
"}\n"
"")
        self.showChambre_Btn.setObjectName("showChambre_Btn")
        self.allReservation_btn = QtWidgets.QPushButton(self.centralwidget)
        self.allReservation_btn.setGeometry(QtCore.QRect(1440, 490, 411, 71))
        self.allReservation_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.allReservation_btn.setFont(font)
        self.allReservation_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allReservation_btn.setStyleSheet("#allReservation_btn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(195, 15, 177);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(170, 8, 108);\n"
"}\n"
"#allReservation_btn:hover:pressed{\n"
"background-color: rgb(255, 160, 248);\n"
"}")
        self.allReservation_btn.setObjectName("allReservation_btn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 550, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(9, 28, 149);")
        self.label_6.setObjectName("label_6")
        self.allReservation_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.allReservation_tableWidget.setGeometry(QtCore.QRect(10, 600, 1851, 361))
        self.allReservation_tableWidget.setStyleSheet("border: 3px Solid rgb(3, 168, 17);\n"
"")
        self.allReservation_tableWidget.setObjectName("allReservation_tableWidget")
        self.allReservation_tableWidget.setColumnCount(14)
        self.allReservation_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.allReservation_tableWidget.setHorizontalHeaderItem(13, item)
        RESERVATIONMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RESERVATIONMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1870, 29))
        self.menubar.setObjectName("menubar")
        RESERVATIONMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RESERVATIONMainWindow)
        self.statusbar.setObjectName("statusbar")
        RESERVATIONMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RESERVATIONMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RESERVATIONMainWindow)

    def retranslateUi(self, RESERVATIONMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RESERVATIONMainWindow.setWindowTitle(_translate("RESERVATIONMainWindow", "MainWindow"))
        self.Search_btn.setText(_translate("RESERVATIONMainWindow", "Search "))
        self.NUM_CHAMBRE_input.setPlaceholderText(_translate("RESERVATIONMainWindow", "NUM_CHAMBRE    "))
        self.label.setText(_translate("RESERVATIONMainWindow", "RESERVATION"))
        self.Add_btn.setText(_translate("RESERVATIONMainWindow", "Add "))
        self.NUM_VISITEUR_input.setPlaceholderText(_translate("RESERVATIONMainWindow", "NUM_VISITEUR    "))
        self.Delete_btn.setText(_translate("RESERVATIONMainWindow", "Delete "))
        self.NUM_RESERVATION_input.setPlaceholderText(_translate("RESERVATIONMainWindow", "NUM_RESERVATION"))
        self.label_2.setText(_translate("RESERVATIONMainWindow", "DATE_DEB  :"))
        self.label_3.setText(_translate("RESERVATIONMainWindow", "DATE_FIN  :"))
        self.Clear_btn.setText(_translate("RESERVATIONMainWindow", "Clear  "))
        self.label_4.setText(_translate("RESERVATIONMainWindow", "Reservation information list  :"))
        self.label_5.setText(_translate("RESERVATIONMainWindow", "PRICE :"))
        self.Price.setText(_translate("RESERVATIONMainWindow", "0000 DH"))
        self.showChambre_Btn.setText(_translate("RESERVATIONMainWindow", "Show Chambre"))
        self.allReservation_btn.setText(_translate("RESERVATIONMainWindow", "All Reservation "))
        self.label_6.setText(_translate("RESERVATIONMainWindow", "All Reservation list  :"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RESERVATIONMainWindow", "NUM_RESERVATION"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RESERVATIONMainWindow", "NUM_VISITEUR"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("RESERVATIONMainWindow", "NUM_CHAMBRE"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("RESERVATIONMainWindow", "DATE_DEB"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("RESERVATIONMainWindow", "DATE_FIN"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("RESERVATIONMainWindow", "CIN"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("RESERVATIONMainWindow", "NOM"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("RESERVATIONMainWindow", "PRENOM"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("RESERVATIONMainWindow", "ADRESSE"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("RESERVATIONMainWindow", "TEL"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("RESERVATIONMainWindow", "EMAIL"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("RESERVATIONMainWindow", "ETAGE"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("RESERVATIONMainWindow", "DESCRIPTION"))
        item = self.allReservation_tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("RESERVATIONMainWindow", "PRIX"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RESERVATIONMainWindow = QtWidgets.QMainWindow()
    ui = Ui_RESERVATIONMainWindow()
    ui.setupUi(RESERVATIONMainWindow)
    RESERVATIONMainWindow.show()
    sys.exit(app.exec_())
